import {
  cloneOAuthProxyJsonObject,
  decodeOAuthProxyRecord,
  encodeOAuthProxyRecord,
  readOAuthProxyRecord,
  type AccessTokenRecord,
  type AuthorizationCodeRecord,
  type ConsentTransactionRecord,
  type LocalClientMetadata,
  type LocalClientRecord,
  type OAuthProxyJsonObject,
  type RefreshAttemptRecord,
  type RefreshFamilyRecord,
  type RefreshOwnerRecord,
  type RefreshTokenRecord,
  type StoredUpstreamTokenSet,
  type UpstreamCallbackRecord,
  type UpstreamGrantRecord,
} from "./authorization-records.js";
import type { OAuthProxyStore, OAuthProxyStoreTransaction } from "./store.js";

const HANDLE_BYTES = 32;
const DEFAULT_BROWSER_TRANSACTION_MS = 10 * 60 * 1000;
const DEFAULT_AUTHORIZATION_CODE_MS = 60 * 1000;
const DEFAULT_ACCESS_TOKEN_MS = 5 * 60 * 1000;
const DEFAULT_REFRESH_IDLE_MS = 30 * 24 * 60 * 60 * 1000;
const DEFAULT_REFRESH_FAMILY_MS = 90 * 24 * 60 * 60 * 1000;
const DEFAULT_CLIENT_REGISTRATION_MS = 365 * 24 * 60 * 60 * 1000;
const DEFAULT_REFRESH_ATTEMPT_MS = 10 * 60 * 1000;
const MIN_TTL_MS = 1000;
const MAX_TTL_MS = 365 * 24 * 60 * 60 * 1000;
const encoder = new TextEncoder();

type CryptoImplementation = Pick<Crypto, "getRandomValues" | "subtle">;

/** @internal Configurable lifetimes for local OAuth proxy state. */
export interface OAuthAuthorizationCoreTtls {
  readonly browserTransactionMs?: number;
  readonly authorizationCodeMs?: number;
  readonly accessTokenMs?: number;
  readonly refreshIdleMs?: number;
  readonly refreshFamilyMs?: number;
  readonly clientRegistrationMs?: number;
  readonly refreshAttemptMs?: number;
}

/** @internal Construction options for the embedded local authorization server core. */
export interface OAuthAuthorizationCoreOptions {
  /** Already-resolved store boundary, encrypted when persistence requires it. */
  readonly store: OAuthProxyStore;
  readonly crypto?: CryptoImplementation;
  readonly now?: () => number;
  readonly ttls?: OAuthAuthorizationCoreTtls;
}

/** @internal Dynamically registered public downstream client. */
export interface RegisteredLocalClient extends LocalClientMetadata {
  readonly clientId: string;
  readonly createdAt: number;
  readonly expiresAt: number;
}

/** @internal Input for a browser consent transaction. */
export interface CreateConsentTransactionInput {
  readonly clientId: string;
  readonly redirectUri: string;
  readonly resource: string;
  readonly scopes: readonly string[];
  readonly downstreamState: string;
  readonly codeChallenge: string;
  readonly browserBinding: string;
}

/** @internal Raw browser handles that must be sent back before consent is accepted. */
export interface CreatedConsentTransaction {
  readonly transactionId: string;
  readonly csrfToken: string;
  readonly expiresAt: number;
}

/** @internal Input for consuming a consent decision. */
export interface ConsumeConsentTransactionInput {
  readonly transactionId: string;
  readonly csrfToken: string;
  readonly browserBinding: string;
}

/** @internal Input persisted while the browser is at the upstream provider. */
export interface CreateUpstreamCallbackInput {
  /** State generated by the upstream OAuth client for this authorization request. */
  readonly upstreamState: string;
  readonly clientId: string;
  readonly redirectUri: string;
  readonly resource: string;
  readonly scopes: readonly string[];
  readonly downstreamState: string;
  readonly downstreamCodeChallenge: string;
  readonly browserBinding: string;
  readonly upstreamCodeVerifier: string;
  readonly upstreamRedirectUri: string;
  readonly upstreamNonce?: string;
  readonly upstreamResource?: string;
}

/** @internal Browser callback state returned to the upstream authorization request. */
export interface CreatedUpstreamCallback {
  readonly state: string;
  readonly expiresAt: number;
}

/** @internal Input for consuming and browser-binding an upstream callback. */
export interface ConsumeUpstreamCallbackInput {
  readonly state: string;
  readonly browserBinding: string;
}

/** @internal Input for persisting a verified upstream grant. */
export interface CreateUpstreamGrantInput {
  readonly tokens: StoredUpstreamTokenSet;
  readonly userPayload: OAuthProxyJsonObject;
  readonly expiresAt?: number;
}

/** @internal Atomically persists a pending grant and mints its one-time local code. */
export interface PersistGrantAndIssueAuthorizationCodeInput {
  readonly clientId: string;
  readonly redirectUri: string;
  readonly resource: string;
  readonly scopes: readonly string[];
  readonly codeChallenge: string;
  readonly grant: CreateUpstreamGrantInput;
}

/** @internal Input for the downstream authorization-code grant. */
export interface ExchangeAuthorizationCodeInput {
  readonly code: string;
  readonly clientId: string;
  readonly redirectUri: string;
  readonly resource: string;
  readonly codeVerifier: string;
}

/** @internal Locally issued opaque bearer token set. */
export interface LocalOAuthTokenSet {
  readonly accessToken: string;
  readonly refreshToken: string;
  readonly tokenType: "Bearer";
  readonly expiresIn: number;
  readonly scope: string;
}

/** @internal Result of validating a local access token for the MCP resource. */
export interface ValidatedLocalAccess {
  readonly clientId: string;
  readonly resource: string;
  readonly scopes: readonly string[];
  readonly userPayload: OAuthProxyJsonObject;
  readonly providerAccessToken: string;
  readonly providerTokenType: string;
  readonly providerAccessTokenExpiresAt?: number;
  readonly expiresAt: number;
}

/** @internal Binding required when rotating a downstream refresh token. */
export interface RotateRefreshTokenInput {
  readonly refreshToken: string;
  readonly clientId: string;
  readonly resource: string;
}

/** @internal State returned before a caller performs exactly one upstream refresh. */
export interface BegunUpstreamRefresh {
  readonly attemptToken: string;
  readonly clientId: string;
  readonly resource: string;
  readonly scopes: readonly string[];
  readonly upstreamTokens: StoredUpstreamTokenSet;
  readonly userPayload: OAuthProxyJsonObject;
  readonly expiresAt: number;
}

/** @internal Completes an upstream refresh and optionally rotates upstream tokens. */
export interface CompleteUpstreamRefreshInput {
  readonly attemptToken: string;
  readonly updatedGrant?: CreateUpstreamGrantInput;
}

/** @internal Marks an uncertain upstream refresh outcome as unusable. */
export interface MarkUpstreamRefreshAmbiguousInput {
  readonly attemptToken: string;
}

/** @internal Local RFC 7009-style revocation input. */
export interface RevokeLocalTokenInput {
  readonly token: string;
  readonly tokenTypeHint?: string;
}

/** @internal Secret-safe, typed failure from local authorization state handling. */
export class OAuthAuthorizationCoreError extends Error {
  readonly code:
    | "invalid_client"
    | "invalid_request"
    | "invalid_grant"
    | "invalid_token"
    | "temporarily_unavailable"
    | "upstream_reauthorization_required";

  /** Creates a normalized local OAuth failure without embedding secret state. */
  constructor(
    code: OAuthAuthorizationCoreError["code"],
    message = "OAuth proxy request could not be completed"
  ) {
    super(message);
    this.name = "OAuthAuthorizationCoreError";
    this.code = code;
  }
}

/**
 * @internal Persistence-backed core for the OAuth proxy's local authorization
 * server. HTTP parsing, consent rendering, and upstream network calls live above
 * this boundary.
 */
export class OAuthAuthorizationCore {
  readonly #store: OAuthProxyStore;
  readonly #crypto: CryptoImplementation;
  readonly #now: () => number;
  readonly #ttls: Required<OAuthAuthorizationCoreTtls>;

  /** Validates the persistence, Web Crypto, clock, and TTL dependencies. */
  constructor(options: OAuthAuthorizationCoreOptions) {
    if (typeof options !== "object" || options === null) {
      throw new TypeError("OAuth authorization core options must be an object");
    }
    if (typeof options.store !== "object" || options.store === null) {
      throw new TypeError("OAuth authorization core requires a resolved store");
    }
    this.#store = options.store;
    this.#crypto = options.crypto ?? globalThis.crypto;
    if (
      typeof this.#crypto?.getRandomValues !== "function" ||
      typeof this.#crypto?.subtle !== "object"
    ) {
      throw new TypeError("OAuth authorization core requires Web Crypto");
    }
    this.#now = options.now ?? Date.now;
    this.#ttls = resolveTtls(options.ttls);
  }

  /** Registers a unique local public client. Redirect policy is enforced by the route layer. */
  async registerClient(
    metadata: LocalClientMetadata
  ): Promise<RegisteredLocalClient> {
    const normalized = normalizeClientMetadata(metadata);
    const now = this.#timestamp();
    const expiresAt = now + this.#ttls.clientRegistrationMs;
    const record: LocalClientRecord = {
      kind: "client",
      metadata: normalized,
      createdAt: now,
      expiresAt,
    };
    for (let attempt = 0; attempt < 4; attempt += 1) {
      const clientId = this.#randomHandle();
      const key = await this.#lookupKey("client", clientId);
      const result = await this.#store.create(
        key,
        encodeOAuthProxyRecord(record),
        expiresAt
      );
      if (result.status === "created") {
        return { clientId, ...normalized, createdAt: now, expiresAt };
      }
    }
    throw new OAuthAuthorizationCoreError("temporarily_unavailable");
  }

  /** Reads a live local client by its public identifier. */
  async getClient(
    clientId: string
  ): Promise<RegisteredLocalClient | undefined> {
    requireHandle(clientId, "clientId");
    const key = await this.#lookupKey("client", clientId);
    const result = await this.#store.read(key);
    if (result.status !== "found") return undefined;
    const record = decodeOAuthProxyRecord(result.payload, "client");
    if (record.expiresAt <= this.#timestamp()) return undefined;
    return {
      clientId,
      ...record.metadata,
      createdAt: record.createdAt,
      expiresAt: record.expiresAt,
    };
  }

  /** Creates a one-time, CSRF- and browser-bound local consent transaction. */
  async createConsentTransaction(
    input: CreateConsentTransactionInput
  ): Promise<CreatedConsentTransaction> {
    validateAuthorizationBinding(input);
    requireHandle(input.browserBinding, "browserBinding");
    const transactionId = this.#randomHandle();
    const csrfToken = this.#randomHandle();
    const now = this.#timestamp();
    const expiresAt = now + this.#ttls.browserTransactionMs;
    const record: ConsentTransactionRecord = {
      kind: "consent",
      clientId: input.clientId,
      redirectUri: input.redirectUri,
      resource: input.resource,
      scopes: normalizeScopes(input.scopes),
      downstreamState: input.downstreamState,
      codeChallenge: validateCodeChallenge(input.codeChallenge),
      csrfHash: await this.#hashText(csrfToken),
      browserBindingHash: await this.#hashText(input.browserBinding),
      createdAt: now,
      expiresAt,
    };
    await this.#createUnique(
      await this.#lookupKey("consent", transactionId),
      record,
      expiresAt
    );
    return { transactionId, csrfToken, expiresAt };
  }

  /** Atomically consumes a consent transaction after CSRF and browser binding checks. */
  async consumeConsentTransaction(
    input: ConsumeConsentTransactionInput
  ): Promise<ConsentTransactionRecord> {
    requireHandle(input.transactionId, "transactionId");
    requireHandle(input.csrfToken, "csrfToken");
    requireHandle(input.browserBinding, "browserBinding");
    const key = await this.#lookupKey("consent", input.transactionId);
    const csrfHash = await this.#hashText(input.csrfToken);
    const browserHash = await this.#hashText(input.browserBinding);
    return this.#store.transaction([key], async (transaction) => {
      const consumed = await transaction.consume(key);
      if (consumed.status !== "consumed") throw invalidGrant();
      const record = decodeOAuthProxyRecord(consumed.payload, "consent");
      if (
        record.expiresAt <= this.#timestamp() ||
        !constantTimeTextEqual(record.csrfHash, csrfHash) ||
        !constantTimeTextEqual(record.browserBindingHash, browserHash)
      ) {
        throw invalidGrant();
      }
      return record;
    });
  }

  /** Creates the one-time state record used around the upstream authorization redirect. */
  async createUpstreamCallbackTransaction(
    input: CreateUpstreamCallbackInput
  ): Promise<CreatedUpstreamCallback> {
    validateAuthorizationBinding({
      ...input,
      codeChallenge: input.downstreamCodeChallenge,
    });
    requireHandle(input.browserBinding, "browserBinding");
    requireNonEmptyString(input.upstreamCodeVerifier, "upstreamCodeVerifier");
    requireNonEmptyString(input.upstreamRedirectUri, "upstreamRedirectUri");
    optionalNonEmptyString(input.upstreamNonce, "upstreamNonce");
    optionalNonEmptyString(input.upstreamResource, "upstreamResource");
    requireHandle(input.upstreamState, "upstreamState");
    const state = input.upstreamState;
    const now = this.#timestamp();
    const expiresAt = now + this.#ttls.browserTransactionMs;
    const record: UpstreamCallbackRecord = {
      kind: "upstream-callback",
      clientId: input.clientId,
      redirectUri: input.redirectUri,
      resource: input.resource,
      scopes: normalizeScopes(input.scopes),
      downstreamState: input.downstreamState,
      downstreamCodeChallenge: validateCodeChallenge(
        input.downstreamCodeChallenge
      ),
      browserBindingHash: await this.#hashText(input.browserBinding),
      upstreamCodeVerifier: input.upstreamCodeVerifier,
      upstreamRedirectUri: input.upstreamRedirectUri,
      ...(input.upstreamNonce === undefined
        ? {}
        : { upstreamNonce: input.upstreamNonce }),
      ...(input.upstreamResource === undefined
        ? {}
        : { upstreamResource: input.upstreamResource }),
      createdAt: now,
      expiresAt,
    };
    await this.#createUnique(
      await this.#lookupKey("callback", state),
      record,
      expiresAt
    );
    return { state, expiresAt };
  }

  /** Consumes upstream callback state and enforces the original browser binding. */
  async consumeUpstreamCallbackTransaction(
    input: ConsumeUpstreamCallbackInput
  ): Promise<UpstreamCallbackRecord> {
    requireHandle(input.state, "state");
    requireHandle(input.browserBinding, "browserBinding");
    const key = await this.#lookupKey("callback", input.state);
    const browserHash = await this.#hashText(input.browserBinding);
    return this.#store.transaction([key], async (transaction) => {
      const consumed = await transaction.consume(key);
      if (consumed.status !== "consumed") throw invalidGrant();
      const record = decodeOAuthProxyRecord(
        consumed.payload,
        "upstream-callback"
      );
      if (
        record.expiresAt <= this.#timestamp() ||
        !constantTimeTextEqual(record.browserBindingHash, browserHash)
      ) {
        throw invalidGrant();
      }
      return record;
    });
  }

  /** Atomically stores a code-leased upstream grant and its bound downstream code. */
  async persistGrantAndIssueAuthorizationCode(
    input: PersistGrantAndIssueAuthorizationCodeInput
  ): Promise<{ code: string; expiresAt: number }> {
    validateTokenBinding(input);
    const now = this.#timestamp();
    const expiresAt = now + this.#ttls.authorizationCodeMs;
    const grantRef = await this.#randomReference();
    const code = this.#randomHandle();
    const grantKeyValue = grantKey(grantRef);
    const codeKey = await this.#lookupKey("code", code);
    const grant = upstreamGrantRecord(input.grant, now, expiresAt);
    const codeRecord: AuthorizationCodeRecord = {
      kind: "authorization-code",
      clientId: input.clientId,
      redirectUri: input.redirectUri,
      resource: input.resource,
      scopes: normalizeScopes(input.scopes),
      codeChallenge: validateCodeChallenge(input.codeChallenge),
      grantRef,
      createdAt: now,
      expiresAt,
    };
    await this.#store.transaction(
      [grantKeyValue, codeKey],
      async (transaction) => {
        assertCreated(
          await transaction.create(
            grantKeyValue,
            encodeOAuthProxyRecord(grant),
            expiresAt
          )
        );
        assertCreated(
          await transaction.create(
            codeKey,
            encodeOAuthProxyRecord(codeRecord),
            expiresAt
          )
        );
      }
    );
    return { code, expiresAt };
  }

  /** Atomically consumes a code and creates access, refresh, family, and replay-owner state. */
  async exchangeAuthorizationCode(
    input: ExchangeAuthorizationCodeInput
  ): Promise<LocalOAuthTokenSet> {
    requireHandle(input.code, "code");
    requireNonEmptyString(input.clientId, "clientId");
    requireNonEmptyString(input.redirectUri, "redirectUri");
    requireNonEmptyString(input.resource, "resource");
    validateCodeVerifier(input.codeVerifier);
    const codeKey = await this.#lookupKey("code", input.code);
    const initial = await this.#store.read(codeKey);
    if (initial.status !== "found") throw invalidGrant();
    const preview = decodeOAuthProxyRecord(
      initial.payload,
      "authorization-code"
    );
    const familyRef = await this.#randomReference();
    const accessToken = this.#randomHandle();
    const refreshToken = this.#randomHandle();
    const accessKey = await this.#lookupKey("access", accessToken);
    const refreshKey = await this.#lookupKey("refresh", refreshToken);
    const ownerKey = await this.#lookupKey("refresh-owner", refreshToken);
    const familyKey = refreshFamilyKey(familyRef);
    const currentGrantKey = grantKey(preview.grantRef);
    return this.#store.transaction(
      [codeKey, accessKey, refreshKey, ownerKey, familyKey, currentGrantKey],
      async (transaction) => {
        const consumed = await transaction.consume(codeKey);
        if (consumed.status !== "consumed") throw invalidGrant();
        const code = decodeOAuthProxyRecord(
          consumed.payload,
          "authorization-code"
        );
        await this.#validateCodeExchange(input, code);
        const grant = await readOAuthProxyRecord(
          transaction,
          grantKey(code.grantRef),
          "upstream-grant"
        );
        if (grant === undefined) {
          throw new OAuthAuthorizationCoreError(
            "upstream_reauthorization_required"
          );
        }
        return this.#createTokenState(transaction, {
          accessKey,
          accessToken,
          refreshKey,
          refreshToken,
          ownerKey,
          familyKey,
          familyRef,
          clientId: code.clientId,
          resource: code.resource,
          scopes: code.scopes,
          grantRef: code.grantRef,
          grantKey: grantKey(code.grantRef),
          grant,
          createFamily: true,
        });
      }
    );
  }

  /** Validates a local access token, its grant, and its non-revoked refresh family. */
  async validateAccessToken(
    accessToken: string,
    resource: string
  ): Promise<ValidatedLocalAccess> {
    requireHandle(accessToken, "accessToken");
    requireNonEmptyString(resource, "resource");
    const accessKey = await this.#lookupKey("access", accessToken);
    const initial = await this.#store.read(accessKey);
    if (initial.status !== "found") throw invalidToken();
    const preview = decodeOAuthProxyRecord(initial.payload, "access-token");
    const familyKey = refreshFamilyKey(preview.familyRef);
    const currentGrantKey = grantKey(preview.grantRef);
    const validated = await this.#store.transaction(
      [accessKey, familyKey, currentGrantKey],
      async (transaction) => {
        const access = await readOAuthProxyRecord(
          transaction,
          accessKey,
          "access-token"
        );
        const family = await readOAuthProxyRecord(
          transaction,
          familyKey,
          "refresh-family"
        );
        const grant = await readOAuthProxyRecord(
          transaction,
          currentGrantKey,
          "upstream-grant"
        );
        const now = this.#timestamp();
        if (
          access === undefined ||
          family === undefined ||
          grant === undefined ||
          access.expiresAt <= now ||
          family.absoluteExpiresAt <= now ||
          family.status === "revoked" ||
          access.resource !== resource ||
          access.familyRef !== preview.familyRef ||
          access.grantRef !== preview.grantRef ||
          family.grantRef !== access.grantRef
        ) {
          throw invalidToken();
        }
        if (
          family.status === "refreshing" &&
          family.refreshAttemptExpiresAt !== undefined &&
          family.refreshAttemptExpiresAt <= now
        ) {
          assertReplaced(
            await transaction.replace(
              familyKey,
              encodeOAuthProxyRecord(revokeFamilyRecord(family)),
              family.absoluteExpiresAt
            )
          );
          return undefined;
        }
        return {
          clientId: access.clientId,
          resource: access.resource,
          scopes: [...access.scopes],
          userPayload: cloneOAuthProxyJsonObject(grant.userPayload),
          providerAccessToken: grant.tokens.accessToken,
          providerTokenType: grant.tokens.tokenType,
          ...(grant.tokens.accessTokenExpiresAt === undefined
            ? {}
            : {
                providerAccessTokenExpiresAt: grant.tokens.accessTokenExpiresAt,
              }),
          expiresAt: access.expiresAt,
        };
      }
    );
    if (validated === undefined) throw invalidToken();
    return validated;
  }

  /** Atomically rotates a downstream refresh token without an upstream network operation. */
  async rotateRefreshToken(
    input: RotateRefreshTokenInput
  ): Promise<LocalOAuthTokenSet> {
    return this.#rotateRefresh(input);
  }

  /**
   * Consumes a refresh token before an upstream network call and returns a
   * one-time completion handle. Callers must never retry the old upstream token.
   */
  async beginUpstreamRefresh(
    input: RotateRefreshTokenInput
  ): Promise<BegunUpstreamRefresh> {
    validateRefreshBinding(input);
    const context = await this.#resolveRefreshContext(input.refreshToken);
    const attemptToken = this.#randomHandle();
    const attemptHash = await this.#hashText(attemptToken);
    const attemptKey = await this.#lookupKey("refresh-attempt", attemptToken);
    const expiresAt = Math.min(
      this.#timestamp() + this.#ttls.refreshAttemptMs,
      context.owner.expiresAt
    );
    const familyPreviewResult = await this.#store.read(context.familyKey);
    if (familyPreviewResult.status !== "found") throw invalidGrant();
    const familyPreview = decodeOAuthProxyRecord(
      familyPreviewResult.payload,
      "refresh-family"
    );
    const currentGrantKey = grantKey(familyPreview.grantRef);
    const result = await this.#store.transaction(
      [
        context.refreshKey,
        context.familyKey,
        context.ownerKey,
        attemptKey,
        currentGrantKey,
      ],
      async (transaction) => {
        const token = await transaction.consume(context.refreshKey);
        if (token.status !== "consumed") {
          await this.#revokeFamilyAfterReplay(
            transaction,
            context.familyKey,
            context.owner.familyRef
          );
          return undefined;
        }
        const refresh = decodeOAuthProxyRecord(token.payload, "refresh-token");
        const family = await readOAuthProxyRecord(
          transaction,
          context.familyKey,
          "refresh-family"
        );
        validateRefreshRecords(
          input,
          refresh,
          family,
          context.owner.familyRef,
          this.#timestamp()
        );
        const refreshing: RefreshFamilyRecord = {
          ...family,
          status: "refreshing",
          refreshAttemptHash: attemptHash,
          refreshAttemptExpiresAt: expiresAt,
        };
        assertReplaced(
          await transaction.replace(
            context.familyKey,
            encodeOAuthProxyRecord(refreshing),
            family.absoluteExpiresAt
          )
        );
        const attempt: RefreshAttemptRecord = {
          kind: "refresh-attempt",
          familyRef: context.owner.familyRef,
          attemptHash,
          expiresAt,
        };
        assertCreated(
          await transaction.create(
            attemptKey,
            encodeOAuthProxyRecord(attempt),
            family.absoluteExpiresAt
          )
        );
        const grant = await readOAuthProxyRecord(
          transaction,
          grantKey(family.grantRef),
          "upstream-grant"
        );
        if (grant === undefined) {
          throw new OAuthAuthorizationCoreError(
            "upstream_reauthorization_required"
          );
        }
        return {
          attemptToken,
          clientId: family.clientId,
          resource: family.resource,
          scopes: [...family.scopes],
          upstreamTokens: cloneUpstreamTokens(grant.tokens),
          userPayload: cloneOAuthProxyJsonObject(grant.userPayload),
          expiresAt,
        };
      }
    );
    if (result === undefined) throw invalidGrant();
    return result;
  }

  /** Completes exactly one begun upstream refresh and mints the next local token generation. */
  async completeUpstreamRefresh(
    input: CompleteUpstreamRefreshInput
  ): Promise<LocalOAuthTokenSet> {
    requireHandle(input.attemptToken, "attemptToken");
    const attemptKey = await this.#lookupKey(
      "refresh-attempt",
      input.attemptToken
    );
    const initial = await this.#store.read(attemptKey);
    if (initial.status !== "found") throw invalidGrant();
    const attempt = decodeOAuthProxyRecord(initial.payload, "refresh-attempt");
    const familyKey = refreshFamilyKey(attempt.familyRef);
    const familyPreviewResult = await this.#store.read(familyKey);
    if (familyPreviewResult.status !== "found") throw invalidGrant();
    const familyPreview = decodeOAuthProxyRecord(
      familyPreviewResult.payload,
      "refresh-family"
    );
    const accessToken = this.#randomHandle();
    const refreshToken = this.#randomHandle();
    const accessKey = await this.#lookupKey("access", accessToken);
    const refreshKey = await this.#lookupKey("refresh", refreshToken);
    const ownerKey = await this.#lookupKey("refresh-owner", refreshToken);
    const newGrantRef =
      input.updatedGrant === undefined
        ? familyPreview.grantRef
        : await this.#randomReference();
    const newGrantKey = grantKey(newGrantRef);
    const keys = [
      attemptKey,
      familyKey,
      accessKey,
      refreshKey,
      ownerKey,
      newGrantKey,
    ];
    if (newGrantKey !== grantKey(familyPreview.grantRef)) {
      keys.push(grantKey(familyPreview.grantRef));
    }
    const completed = await this.#store.transaction(
      keys,
      async (transaction) => {
        const consumed = await transaction.consume(attemptKey);
        if (consumed.status !== "consumed") throw invalidGrant();
        const currentAttempt = decodeOAuthProxyRecord(
          consumed.payload,
          "refresh-attempt"
        );
        const family = await readOAuthProxyRecord(
          transaction,
          familyKey,
          "refresh-family"
        );
        const attemptHash = await this.#hashText(input.attemptToken);
        const now = this.#timestamp();
        if (
          family === undefined ||
          family.status !== "refreshing" ||
          family.refreshAttemptHash === undefined ||
          family.refreshAttemptExpiresAt === undefined ||
          !constantTimeTextEqual(currentAttempt.attemptHash, attemptHash) ||
          !constantTimeTextEqual(family.refreshAttemptHash, attemptHash)
        ) {
          throw invalidGrant();
        }
        if (
          currentAttempt.expiresAt <= now ||
          family.refreshAttemptExpiresAt <= now
        ) {
          assertReplaced(
            await transaction.replace(
              familyKey,
              encodeOAuthProxyRecord(revokeFamilyRecord(family)),
              family.absoluteExpiresAt
            )
          );
          return undefined;
        }
        let grant: UpstreamGrantRecord | undefined;
        if (input.updatedGrant === undefined) {
          grant = await readOAuthProxyRecord(
            transaction,
            grantKey(family.grantRef),
            "upstream-grant"
          );
        } else {
          const expiresAt = Math.min(
            input.updatedGrant.expiresAt ?? family.absoluteExpiresAt,
            family.absoluteExpiresAt
          );
          requireFutureTimestamp(expiresAt, now, "upstream grant expiry");
          grant = upstreamGrantRecord(input.updatedGrant, now, expiresAt);
          assertCreated(
            await transaction.create(
              newGrantKey,
              encodeOAuthProxyRecord(grant),
              expiresAt
            )
          );
          const retired = await transaction.consume(grantKey(family.grantRef));
          if (retired.status !== "consumed") {
            throw new OAuthAuthorizationCoreError(
              "upstream_reauthorization_required"
            );
          }
        }
        if (grant === undefined) {
          throw new OAuthAuthorizationCoreError(
            "upstream_reauthorization_required"
          );
        }
        const activeFamily: RefreshFamilyRecord = {
          kind: "refresh-family",
          clientId: family.clientId,
          resource: family.resource,
          scopes: [...family.scopes],
          grantRef: newGrantRef,
          status: "active",
          createdAt: family.createdAt,
          absoluteExpiresAt: family.absoluteExpiresAt,
        };
        assertReplaced(
          await transaction.replace(
            familyKey,
            encodeOAuthProxyRecord(activeFamily),
            family.absoluteExpiresAt
          )
        );
        return this.#createTokenState(transaction, {
          accessKey,
          accessToken,
          refreshKey,
          refreshToken,
          ownerKey,
          familyKey,
          familyRef: attempt.familyRef,
          clientId: family.clientId,
          resource: family.resource,
          scopes: family.scopes,
          grantRef: newGrantRef,
          grantKey: newGrantKey,
          grant,
          createFamily: false,
        });
      }
    );
    if (completed === undefined) {
      throw new OAuthAuthorizationCoreError(
        "upstream_reauthorization_required"
      );
    }
    return completed;
  }

  /** Revokes a refresh family after a timeout or other ambiguous upstream outcome. */
  async markUpstreamRefreshAmbiguous(
    input: MarkUpstreamRefreshAmbiguousInput
  ): Promise<void> {
    requireHandle(input.attemptToken, "attemptToken");
    const attemptKey = await this.#lookupKey(
      "refresh-attempt",
      input.attemptToken
    );
    const initial = await this.#store.read(attemptKey);
    if (initial.status !== "found") return;
    const attempt = decodeOAuthProxyRecord(initial.payload, "refresh-attempt");
    const familyKey = refreshFamilyKey(attempt.familyRef);
    await this.#store.transaction(
      [attemptKey, familyKey],
      async (transaction) => {
        await transaction.consume(attemptKey);
        await this.#revokeFamilyAfterReplay(
          transaction,
          familyKey,
          attempt.familyRef
        );
      }
    );
  }

  /** Revokes a local access token or refresh family without disclosing whether it existed. */
  async revokeLocalToken(input: RevokeLocalTokenInput): Promise<void> {
    if (!isHandle(input.token)) return;
    // A token type hint is only an optimization hint. Search both namespaces so
    // an incorrect hint cannot leave a live token behind.
    const accessKey = await this.#lookupKey("access", input.token);
    await this.#store.consume(accessKey);
    const ownerKey = await this.#lookupKey("refresh-owner", input.token);
    const ownerResult = await this.#store.read(ownerKey);
    if (ownerResult.status !== "found") return;
    const owner = decodeOAuthProxyRecord(ownerResult.payload, "refresh-owner");
    const familyKey = refreshFamilyKey(owner.familyRef);
    const refreshKey = await this.#lookupKey("refresh", input.token);
    await this.#store.transaction(
      [refreshKey, ownerKey, familyKey],
      async (transaction) => {
        await transaction.consume(refreshKey);
        await this.#revokeFamilyAfterReplay(
          transaction,
          familyKey,
          owner.familyRef
        );
      }
    );
  }

  async #rotateRefresh(
    input: RotateRefreshTokenInput
  ): Promise<LocalOAuthTokenSet> {
    validateRefreshBinding(input);
    const context = await this.#resolveRefreshContext(input.refreshToken);
    const familyPreviewResult = await this.#store.read(context.familyKey);
    if (familyPreviewResult.status !== "found") throw invalidGrant();
    const familyPreview = decodeOAuthProxyRecord(
      familyPreviewResult.payload,
      "refresh-family"
    );
    const grantKeyValue = grantKey(familyPreview.grantRef);
    const accessToken = this.#randomHandle();
    const refreshToken = this.#randomHandle();
    const accessKey = await this.#lookupKey("access", accessToken);
    const refreshKey = await this.#lookupKey("refresh", refreshToken);
    const ownerKey = await this.#lookupKey("refresh-owner", refreshToken);
    const result = await this.#store.transaction(
      [
        context.refreshKey,
        context.ownerKey,
        context.familyKey,
        grantKeyValue,
        accessKey,
        refreshKey,
        ownerKey,
      ],
      async (transaction) => {
        const consumed = await transaction.consume(context.refreshKey);
        if (consumed.status !== "consumed") {
          await this.#revokeFamilyAfterReplay(
            transaction,
            context.familyKey,
            context.owner.familyRef
          );
          return undefined;
        }
        const refresh = decodeOAuthProxyRecord(
          consumed.payload,
          "refresh-token"
        );
        const family = await readOAuthProxyRecord(
          transaction,
          context.familyKey,
          "refresh-family"
        );
        validateRefreshRecords(
          input,
          refresh,
          family,
          context.owner.familyRef,
          this.#timestamp()
        );
        const grant = await readOAuthProxyRecord(
          transaction,
          grantKey(family.grantRef),
          "upstream-grant"
        );
        if (grant === undefined) {
          throw new OAuthAuthorizationCoreError(
            "upstream_reauthorization_required"
          );
        }
        return this.#createTokenState(transaction, {
          accessKey,
          accessToken,
          refreshKey,
          refreshToken,
          ownerKey,
          familyKey: context.familyKey,
          familyRef: context.owner.familyRef,
          clientId: family.clientId,
          resource: family.resource,
          scopes: family.scopes,
          grantRef: family.grantRef,
          grantKey: grantKey(family.grantRef),
          grant,
          createFamily: false,
        });
      }
    );
    if (result === undefined) throw invalidGrant();
    return result;
  }

  async #resolveRefreshContext(refreshToken: string): Promise<{
    refreshKey: string;
    ownerKey: string;
    familyKey: string;
    owner: RefreshOwnerRecord;
  }> {
    requireHandle(refreshToken, "refreshToken");
    const refreshKey = await this.#lookupKey("refresh", refreshToken);
    const ownerKey = await this.#lookupKey("refresh-owner", refreshToken);
    const result = await this.#store.read(ownerKey);
    if (result.status !== "found") throw invalidGrant();
    const owner = decodeOAuthProxyRecord(result.payload, "refresh-owner");
    return {
      refreshKey,
      ownerKey,
      familyKey: refreshFamilyKey(owner.familyRef),
      owner,
    };
  }

  async #createTokenState(
    transaction: OAuthProxyStoreTransaction,
    input: {
      accessKey: string;
      accessToken: string;
      refreshKey: string;
      refreshToken: string;
      ownerKey: string;
      familyKey: string;
      familyRef: string;
      clientId: string;
      resource: string;
      scopes: readonly string[];
      grantRef: string;
      grantKey: string;
      grant: UpstreamGrantRecord;
      createFamily: boolean;
    }
  ): Promise<LocalOAuthTokenSet> {
    const now = this.#timestamp();
    const familyExpiresAt = input.createFamily
      ? now + this.#ttls.refreshFamilyMs
      : await existingFamilyExpiry(transaction, input.familyKey);
    if (familyExpiresAt <= now) throw invalidGrant();
    let grant = input.grant;
    if (input.createFamily && grant.expiresAt !== familyExpiresAt) {
      grant = { ...grant, expiresAt: familyExpiresAt };
      assertReplaced(
        await transaction.replace(
          input.grantKey,
          encodeOAuthProxyRecord(grant),
          familyExpiresAt
        )
      );
    }
    const accessExpiresAt = Math.min(
      now + this.#ttls.accessTokenMs,
      grant.tokens.accessTokenExpiresAt ?? Number.MAX_SAFE_INTEGER,
      grant.expiresAt,
      familyExpiresAt
    );
    if (accessExpiresAt - now < 1000) {
      throw new OAuthAuthorizationCoreError(
        "upstream_reauthorization_required"
      );
    }
    const refreshExpiresAt = Math.min(
      now + this.#ttls.refreshIdleMs,
      familyExpiresAt
    );
    const accessRecord: AccessTokenRecord = {
      kind: "access-token",
      clientId: input.clientId,
      resource: input.resource,
      scopes: [...input.scopes],
      grantRef: input.grantRef,
      familyRef: input.familyRef,
      createdAt: now,
      expiresAt: accessExpiresAt,
    };
    const refreshRecord: RefreshTokenRecord = {
      kind: "refresh-token",
      familyRef: input.familyRef,
      createdAt: now,
      expiresAt: refreshExpiresAt,
    };
    const ownerRecord: RefreshOwnerRecord = {
      kind: "refresh-owner",
      familyRef: input.familyRef,
      expiresAt: familyExpiresAt,
    };
    if (input.createFamily) {
      const family: RefreshFamilyRecord = {
        kind: "refresh-family",
        clientId: input.clientId,
        resource: input.resource,
        scopes: [...input.scopes],
        grantRef: input.grantRef,
        status: "active",
        createdAt: now,
        absoluteExpiresAt: familyExpiresAt,
      };
      assertCreated(
        await transaction.create(
          input.familyKey,
          encodeOAuthProxyRecord(family),
          familyExpiresAt
        )
      );
    }
    assertCreated(
      await transaction.create(
        input.accessKey,
        encodeOAuthProxyRecord(accessRecord),
        accessExpiresAt
      )
    );
    assertCreated(
      await transaction.create(
        input.refreshKey,
        encodeOAuthProxyRecord(refreshRecord),
        refreshExpiresAt
      )
    );
    assertCreated(
      await transaction.create(
        input.ownerKey,
        encodeOAuthProxyRecord(ownerRecord),
        familyExpiresAt
      )
    );
    return {
      accessToken: input.accessToken,
      refreshToken: input.refreshToken,
      tokenType: "Bearer",
      expiresIn: Math.floor((accessExpiresAt - now) / 1000),
      scope: input.scopes.join(" "),
    };
  }

  async #validateCodeExchange(
    input: ExchangeAuthorizationCodeInput,
    code: AuthorizationCodeRecord
  ): Promise<void> {
    const expectedChallenge = await this.#s256(input.codeVerifier);
    if (
      code.expiresAt <= this.#timestamp() ||
      code.clientId !== input.clientId ||
      code.redirectUri !== input.redirectUri ||
      code.resource !== input.resource ||
      !constantTimeTextEqual(code.codeChallenge, expectedChallenge)
    ) {
      throw invalidGrant();
    }
  }

  async #revokeFamilyAfterReplay(
    transaction: OAuthProxyStoreTransaction,
    familyKey: string,
    expectedFamilyRef: string
  ): Promise<void> {
    const family = await readOAuthProxyRecord(
      transaction,
      familyKey,
      "refresh-family"
    );
    if (family === undefined) return;
    if (!familyKey.endsWith(expectedFamilyRef)) return;
    if (family.status === "revoked") return;
    const revoked = revokeFamilyRecord(family);
    assertReplaced(
      await transaction.replace(
        familyKey,
        encodeOAuthProxyRecord(revoked),
        family.absoluteExpiresAt
      )
    );
  }

  async #createUnique(
    key: string,
    record:
      | ConsentTransactionRecord
      | UpstreamCallbackRecord
      | UpstreamGrantRecord
      | AuthorizationCodeRecord,
    expiresAt: number
  ): Promise<void> {
    const result = await this.#store.create(
      key,
      encodeOAuthProxyRecord(record),
      expiresAt
    );
    if (result.status !== "created") {
      throw new OAuthAuthorizationCoreError("temporarily_unavailable");
    }
  }

  async #lookupKey(namespace: string, handle: string): Promise<string> {
    return `oauth-proxy:${namespace}:${await this.#hashText(handle)}`;
  }

  async #randomReference(): Promise<string> {
    return this.#hashText(this.#randomHandle());
  }

  #randomHandle(): string {
    const bytes = new Uint8Array(HANDLE_BYTES);
    this.#crypto.getRandomValues(bytes);
    return encodeBase64Url(bytes);
  }

  async #hashText(value: string): Promise<string> {
    const digest = await this.#crypto.subtle.digest(
      "SHA-256",
      encoder.encode(value)
    );
    return encodeBase64Url(new Uint8Array(digest));
  }

  async #s256(verifier: string): Promise<string> {
    validateCodeVerifier(verifier);
    return this.#hashText(verifier);
  }

  #timestamp(): number {
    const value = this.#now();
    if (!Number.isSafeInteger(value) || value < 0) {
      throw new TypeError("OAuth authorization core clock is invalid");
    }
    return value;
  }
}

function upstreamGrantRecord(
  input: CreateUpstreamGrantInput,
  createdAt: number,
  expiresAt: number
): UpstreamGrantRecord {
  validateUpstreamTokens(input.tokens);
  return {
    kind: "upstream-grant",
    tokens: cloneUpstreamTokens(input.tokens),
    userPayload: cloneOAuthProxyJsonObject(input.userPayload),
    createdAt,
    expiresAt,
  };
}

function cloneUpstreamTokens(
  tokens: StoredUpstreamTokenSet
): StoredUpstreamTokenSet {
  return {
    accessToken: tokens.accessToken,
    tokenType: tokens.tokenType,
    ...(tokens.accessTokenExpiresAt === undefined
      ? {}
      : { accessTokenExpiresAt: tokens.accessTokenExpiresAt }),
    ...(tokens.refreshToken === undefined
      ? {}
      : { refreshToken: tokens.refreshToken }),
    ...(tokens.scope === undefined ? {} : { scope: tokens.scope }),
    ...(tokens.idToken === undefined ? {} : { idToken: tokens.idToken }),
  };
}

function validateUpstreamTokens(tokens: StoredUpstreamTokenSet): void {
  if (typeof tokens !== "object" || tokens === null) {
    throw new TypeError("Upstream token set must be an object");
  }
  requireNonEmptyString(tokens.accessToken, "upstream access token");
  requireNonEmptyString(tokens.tokenType, "upstream token type");
  optionalNonEmptyString(tokens.refreshToken, "upstream refresh token");
  optionalNonEmptyString(tokens.scope, "upstream scope");
  optionalNonEmptyString(tokens.idToken, "upstream ID token");
  if (
    tokens.accessTokenExpiresAt !== undefined &&
    (!Number.isSafeInteger(tokens.accessTokenExpiresAt) ||
      tokens.accessTokenExpiresAt < 0)
  ) {
    throw new TypeError("Upstream access token expiry is invalid");
  }
}

async function existingFamilyExpiry(
  transaction: OAuthProxyStoreTransaction,
  familyKey: string
): Promise<number> {
  const family = await readOAuthProxyRecord(
    transaction,
    familyKey,
    "refresh-family"
  );
  if (family === undefined || family.status !== "active") throw invalidGrant();
  return family.absoluteExpiresAt;
}

function validateRefreshRecords(
  input: RotateRefreshTokenInput,
  refresh: RefreshTokenRecord,
  family: RefreshFamilyRecord | undefined,
  expectedFamilyRef: string,
  now: number
): asserts family is RefreshFamilyRecord {
  if (
    family === undefined ||
    family.status !== "active" ||
    refresh.familyRef !== expectedFamilyRef ||
    family.clientId !== input.clientId ||
    family.resource !== input.resource ||
    refresh.expiresAt <= now ||
    family.absoluteExpiresAt <= now
  ) {
    throw invalidGrant();
  }
}

function revokeFamilyRecord(family: RefreshFamilyRecord): RefreshFamilyRecord {
  return {
    kind: "refresh-family",
    clientId: family.clientId,
    resource: family.resource,
    scopes: [...family.scopes],
    grantRef: family.grantRef,
    status: "revoked",
    createdAt: family.createdAt,
    absoluteExpiresAt: family.absoluteExpiresAt,
  };
}

function validateRefreshBinding(input: RotateRefreshTokenInput): void {
  requireHandle(input.refreshToken, "refreshToken");
  requireNonEmptyString(input.clientId, "clientId");
  requireNonEmptyString(input.resource, "resource");
}

function validateAuthorizationBinding(input: {
  clientId: string;
  redirectUri: string;
  resource: string;
  scopes: readonly string[];
  downstreamState: string;
  codeChallenge: string;
}): void {
  validateTokenBinding(input);
  requireNonEmptyString(input.downstreamState, "downstreamState");
}

function validateTokenBinding(input: {
  clientId: string;
  redirectUri: string;
  resource: string;
  scopes: readonly string[];
  codeChallenge: string;
}): void {
  requireNonEmptyString(input.clientId, "clientId");
  requireNonEmptyString(input.redirectUri, "redirectUri");
  requireNonEmptyString(input.resource, "resource");
  normalizeScopes(input.scopes);
  validateCodeChallenge(input.codeChallenge);
}

function normalizeClientMetadata(
  metadata: LocalClientMetadata
): LocalClientMetadata {
  if (typeof metadata !== "object" || metadata === null) {
    throw new TypeError("Local client metadata must be an object");
  }
  if (
    !Array.isArray(metadata.redirectUris) ||
    metadata.redirectUris.length === 0
  ) {
    throw new TypeError("Local client redirectUris must be a non-empty array");
  }
  const redirectUris = metadata.redirectUris.map((uri) => {
    requireNonEmptyString(uri, "redirectUri");
    return uri;
  });
  optionalNonEmptyString(metadata.clientName, "clientName");
  optionalNonEmptyString(metadata.scope, "scope");
  return {
    redirectUris,
    ...(metadata.clientName === undefined
      ? {}
      : { clientName: metadata.clientName }),
    ...(metadata.scope === undefined ? {} : { scope: metadata.scope }),
  };
}

function normalizeScopes(scopes: readonly string[]): readonly string[] {
  if (!Array.isArray(scopes) || scopes.length > 256) {
    throw new TypeError("OAuth scopes must be an array");
  }
  const unique = new Set<string>();
  for (const scope of scopes as readonly unknown[]) {
    requireNonEmptyString(scope, "scope");
    if (/\s/u.test(scope))
      throw new TypeError("OAuth scopes cannot contain whitespace");
    unique.add(scope);
  }
  return [...unique];
}

function validateCodeChallenge(value: string): string {
  if (!/^[A-Za-z0-9_-]{43}$/u.test(value)) {
    throw new TypeError("PKCE S256 code challenge is invalid");
  }
  return value;
}

function validateCodeVerifier(value: string): void {
  if (!/^[A-Za-z0-9._~-]{43,128}$/u.test(value)) {
    throw invalidGrant();
  }
}

function requireHandle(value: string, label: string): void {
  if (!isHandle(value)) {
    throw new TypeError(`${label} is invalid`);
  }
}

function isHandle(value: unknown): value is string {
  return typeof value === "string" && /^[A-Za-z0-9_-]{43}$/u.test(value);
}

function requireReference(value: string, label: string): void {
  requireHandle(value, label);
}

function requireNonEmptyString(
  value: unknown,
  label: string
): asserts value is string {
  if (
    typeof value !== "string" ||
    value.length === 0 ||
    value.length > 131_072
  ) {
    throw new TypeError(`${label} must be a non-empty bounded string`);
  }
}

function optionalNonEmptyString(value: unknown, label: string): void {
  if (value !== undefined) requireNonEmptyString(value, label);
}

function requireFutureTimestamp(
  value: number,
  now: number,
  label: string
): void {
  if (
    !Number.isSafeInteger(value) ||
    value <= now ||
    value > now + MAX_TTL_MS
  ) {
    throw new TypeError(`${label} is invalid`);
  }
}

function resolveTtls(
  options: OAuthAuthorizationCoreTtls = {}
): Required<OAuthAuthorizationCoreTtls> {
  if (typeof options !== "object" || options === null) {
    throw new TypeError("OAuth authorization TTLs must be an object");
  }
  const resolved = {
    browserTransactionMs: ttl(
      options.browserTransactionMs,
      DEFAULT_BROWSER_TRANSACTION_MS,
      "browserTransactionMs"
    ),
    authorizationCodeMs: ttl(
      options.authorizationCodeMs,
      DEFAULT_AUTHORIZATION_CODE_MS,
      "authorizationCodeMs"
    ),
    accessTokenMs: ttl(
      options.accessTokenMs,
      DEFAULT_ACCESS_TOKEN_MS,
      "accessTokenMs"
    ),
    refreshIdleMs: ttl(
      options.refreshIdleMs,
      DEFAULT_REFRESH_IDLE_MS,
      "refreshIdleMs"
    ),
    refreshFamilyMs: ttl(
      options.refreshFamilyMs,
      DEFAULT_REFRESH_FAMILY_MS,
      "refreshFamilyMs"
    ),
    clientRegistrationMs: ttl(
      options.clientRegistrationMs,
      DEFAULT_CLIENT_REGISTRATION_MS,
      "clientRegistrationMs"
    ),
    refreshAttemptMs: ttl(
      options.refreshAttemptMs,
      DEFAULT_REFRESH_ATTEMPT_MS,
      "refreshAttemptMs"
    ),
  };
  if (resolved.refreshIdleMs > resolved.refreshFamilyMs) {
    throw new TypeError("refreshIdleMs cannot exceed refreshFamilyMs");
  }
  return resolved;
}

function ttl(
  value: number | undefined,
  fallback: number,
  label: string
): number {
  const resolved = value ?? fallback;
  if (
    !Number.isSafeInteger(resolved) ||
    resolved < MIN_TTL_MS ||
    resolved > MAX_TTL_MS
  ) {
    throw new TypeError(`${label} must be a bounded integer duration`);
  }
  return resolved;
}

function grantKey(grantRef: string): string {
  requireReference(grantRef, "grantRef");
  return `oauth-proxy:grant:${grantRef}`;
}

function refreshFamilyKey(familyRef: string): string {
  requireReference(familyRef, "familyRef");
  return `oauth-proxy:refresh-family:${familyRef}`;
}

function assertCreated(result: { status: string }): void {
  if (result.status !== "created") {
    throw new OAuthAuthorizationCoreError("temporarily_unavailable");
  }
}

function assertReplaced(result: { status: string }): void {
  if (result.status !== "replaced") throw invalidGrant();
}

function invalidGrant(): OAuthAuthorizationCoreError {
  return new OAuthAuthorizationCoreError(
    "invalid_grant",
    "OAuth grant is invalid"
  );
}

function invalidToken(): OAuthAuthorizationCoreError {
  return new OAuthAuthorizationCoreError(
    "invalid_token",
    "Access token is invalid"
  );
}

function constantTimeTextEqual(left: string, right: string): boolean {
  const leftBytes = encoder.encode(left);
  const rightBytes = encoder.encode(right);
  let difference = leftBytes.byteLength ^ rightBytes.byteLength;
  const length = Math.max(leftBytes.byteLength, rightBytes.byteLength);
  for (let index = 0; index < length; index += 1) {
    difference |=
      (leftBytes[index % Math.max(1, leftBytes.byteLength)] ?? 0) ^
      (rightBytes[index % Math.max(1, rightBytes.byteLength)] ?? 0);
  }
  return difference === 0;
}

function encodeBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary)
    .replace(/\+/gu, "-")
    .replace(/\//gu, "_")
    .replace(/=+$/u, "");
}
